apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: nginz
 name: my-dep
 labels:
  app: ninx
spec:
 replicas: 3
 selector:
  matchLabels:
   app: nginx
 template:
   metadata:
    labels:
     app: nginx
   spec:
    containers:
    - name: nginx
      image: nginx:latest
      ports:
      - containerPort: 80

  
